In [81]:
import numpy as np
import pandas as pd

''' X_t+1 =A* X_t , A= Two state Transition matrix, where t=0,1,2,3,4
  want to predict at time (t+1) based on the observation at time t'''

#P_move(To city /From city) =0.95 ,
#P_move(To city /From Suburbs) =0.03 ,
#P_move(To Suburb /From city) =0.05 ,
#P_move(To Suburbs From Suburbs) =0.95 

A=np.array([[0.95 ,0.3],[0.05 ,0.97]]) # A is the transition probabiity matrix
print("Transition probability matrix =\n",A)

# city population in 2000 is =6,000000 ,Suburbs population in 2000 is =4,00000
c_pop_2000=600000
Sub_pop_2000=400000

#Probability distribution=> PD
PD_city= c_pop_2000/(c_pop_2000+Sub_pop_2000)
PD_Sub=Sub_pop_2000/(c_pop_2000+Sub_pop_2000)

x_0 = np.array([PD_city,PD_Sub])

print("\nProbaility Distribuiton=\n",x_0,"\n")

# Matrix multiplication without inbuild function
Result=np.matmul(A,x_0)
steps=int(input("Enter the iteration no="))
print("Itreation_No_0=",Result)
for i in range(1,steps):
    Result =np.matmul(A,Result)
    print("Itreation_No_",i,"=",Result)

# As for example if I want to compute X_t+1 =A* X_t  whent t=19 ,Hence X_20= A^20 *X_0   , With inbulid library
A_steps = np.linalg.matrix_power(A, steps)

# compute x^n
x_steps = A_steps @ x_0
print("\n Without Library Compute x^n= ",x_steps)


Transition probability matrix =
 [[0.950 0.300]
 [0.050 0.970]]

Probaility Distribuiton=
 [0.600 0.400] 



Enter the iteration no= 200


Itreation_No_0= [0.690 0.418]
Itreation_No_ 1 = [0.781 0.440]
Itreation_No_ 2 = [0.874 0.466]
Itreation_No_ 3 = [0.970 0.496]
Itreation_No_ 4 = [1.070 0.529]
Itreation_No_ 5 = [1.175 0.567]
Itreation_No_ 6 = [1.287 0.609]
Itreation_No_ 7 = [1.405 0.655]
Itreation_No_ 8 = [1.531 0.705]
Itreation_No_ 9 = [1.666 0.761]
Itreation_No_ 10 = [1.811 0.821]
Itreation_No_ 11 = [1.967 0.887]
Itreation_No_ 12 = [2.134 0.959]
Itreation_No_ 13 = [2.315 1.037]
Itreation_No_ 14 = [2.511 1.121]
Itreation_No_ 15 = [2.721 1.213]
Itreation_No_ 16 = [2.949 1.313]
Itreation_No_ 17 = [3.196 1.421]
Itreation_No_ 18 = [3.462 1.538]
Itreation_No_ 19 = [3.751 1.665]
Itreation_No_ 20 = [4.063 1.803]
Itreation_No_ 21 = [4.400 1.952]
Itreation_No_ 22 = [4.766 2.113]
Itreation_No_ 23 = [5.161 2.288]
Itreation_No_ 24 = [5.590 2.478]
Itreation_No_ 25 = [6.054 2.683]
Itreation_No_ 26 = [6.556 2.905]
Itreation_No_ 27 = [7.099 3.145]
Itreation_No_ 28 = [7.688 3.406]
Itreation_No_ 29 = [8.325 3.688]
Itreation_No_ 30 = [9.

In [79]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from colorama import Fore, Back, Style
from termcolor import colored
import simple_colors

####REINFORCEMENT LEARNING ITERATIVE Q_TABLE PREPARE:####

''' X_t+1 =A* X_t , A= Two state Transition matrix, where t=0,1,2,3,4
  want to predict at time (t+1) based on the observation at time t'''

A=np.array([[.5,.2,.3],[.3,.8,.3],[.2, 0,.4]]) # A is the transition probabiity matrix
print("Transition probability matrix =\n",A)

# city population in 2000 is =6,000000 ,Suburbs population in 2000 is =4,00000
C_pop_2000=600000
Sub_pop_2000=300000
Vil_pop_2000=100000

#Probability distribution=> PD
PD_city=C_pop_2000/(C_pop_2000+Sub_pop_2000+Vil_pop_2000)
PD_Sub=Sub_pop_2000/(C_pop_2000+Sub_pop_2000+Vil_pop_2000)
PD_Vil=Vil_pop_2000/(C_pop_2000+Sub_pop_2000+Vil_pop_2000)

x_0 = np.array([PD_city,PD_Sub,PD_Vil])

print("\nProbaility Distribuiton=\n",x_0,"\n")

# Matrix multiplication without inbuild function
Result=np.matmul(A,x_0)
List=[]

steps=int(input(Fore.GREEN +"Enter the iteration no="))
print("\n")
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print("\033[1;31m ","Itreation_No_0=",Result)
for i in range(1,steps):
    Result =np.matmul(A,Result)  
    #print("Itreation_No_", i,"=", Result)  '''It will not provide an exact approximate  to see; please uncomment it'''
    X=Result[0]
    Y=Result[1]
    Z=Result[2]
    temp=[X,Y,Z]
    if((i-1)%2==0):
        print("\033[1;34m ","Itreation_No_",i,"=",temp)
    else:
        print("\033[1;31m ","Itreation_No_",i,"=",temp)

    list=Result.tolist()
    List.append(list)
    if(i>=2):
        #print(List[i-2],List[i-1])
        if (List[i-2]==List[i-1]):
            #print(Fore.GREEN +"\nStopping criteria!= Last 2 consecutive operations are exact same\n")
            print(simple_colors.green("\nStopping criteria!= Last 2 consecutive operations are exact same\n", 'bold'))
            print("\033[1;34m ",List[i-2],"\033[1;31m",List[i-1])
            print(Style.RESET_ALL)
            break
                  
#print("Hi",len(List))
print("Append the convergence value in a List For Future use :\n",List)
   

Transition probability matrix =
 [[0.500 0.200 0.300]
 [0.300 0.800 0.300]
 [0.200 0.000 0.400]]

Probaility Distribuiton=
 [0.600 0.300 0.100] 



Enter the iteration no= 5000




  Itreation_No_0= [0.390 0.450 0.160]
  Itreation_No_ 1 = [0.333, 0.525, 0.14200000000000002]
  Itreation_No_ 2 = [0.31410000000000005, 0.5625, 0.12340000000000001]
  Itreation_No_ 3 = [0.30657, 0.58125, 0.11218000000000003]
  Itreation_No_ 4 = [0.30318900000000004, 0.5906250000000001, 0.10618600000000003]
  Itreation_No_ 5 = [0.30157530000000005, 0.5953125000000001, 0.10311220000000003]
  Itreation_No_ 6 = [0.3007838100000001, 0.5976562500000001, 0.10155994000000002]
  Itreation_No_ 7 = [0.3003911370000001, 0.5988281250000002, 0.10078073800000004]
  Itreation_No_ 8 = [0.3001954149000001, 0.5994140625000002, 0.10039052260000003]
  Itreation_No_ 9 = [0.3000976767300001, 0.5997070312500002, 0.10019529202000005]
  Itreation_No_ 10 = [0.3000488322210001, 0.5998535156250002, 0.10009765215400004]
  Itreation_No_ 11 = [0.3000244148817001, 0.5999267578125003, 0.10004882730580004]
  Itreation_No_ 12 = [0.3000122071950901, 0.5999633789062503, 0.10002441389866004]
  Itreation_No_ 13 = [0.300006